# name: Weather ETL Automation

# on:
#   schedule:
#     - cron: "0 0 * * *" # Run daily at midnight UTC
#   workflow_dispatch: # Allow manual trigger of the workflow

# jobs:
#   run-etl:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.9"

#     - name: Install dependencies
#       run: pip install -r requirements.txt

#     # Add the config.yaml file if it is excluded from the repo
#     - name: Create config.yaml
#       run: |
# # TO DO: create secret in github for the api key and call it here 
#     - name: Run the ETL pipeline
#       run: python extract/fetch_weather.py
